/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#100729',
        surface: '#0c1324',
        'inverse-surface': '#dce1fb',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-tertiary': '#00344d',
        'secondary-fixed': '#f0dbff',
        'on-secondary': '#490080',
        'on-primary': '#1000a9',
        'on-primary-fixed': '#07006c',
        'surface-bright': '#33394c',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-surface-variant': '#c7c4d7',
        'surface-container': '#191f31',
        'secondary-container': '#6f00be',
        'on-secondary-container': '#d6a9ff',
        'surface-container-lowest': '#070d1f',
        'on-background': '#dce1fb',
        'inverse-on-surface': '#2a3043',
        'on-error': '#690005',
        'surface-container-low': '#151b2d',
        'on-secondary-fixed-variant': '#6900b3',
        'tertiary-container': '#009ada',
        'on-primary-container': '#0d0096',
        'surface-container-highest': '#2e3447',
        'primary-fixed-dim': '#c0c1ff',
        tertiary: '#89ceff',
        'on-tertiary-fixed-variant': '#004c6e',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#89ceff',
        secondary: '#ddb7ff',
        'surface-container-high': '#23293c',
        'surface-dim': '#0c1324',
        'outline-variant': '#464554',
        outline: '#908fa0',
        'on-surface': '#dce1fb',
        'secondary-fixed-dim': '#ddb7ff',
        'surface-variant': '#2e3447',
        'primary-fixed': '#e1e0ff',
        'primary-container': '#8083ff',
        'tertiary-fixed': '#c9e6ff',
        'on-tertiary-container': '#002d43',
        primary: '#c0c1ff',
        'on-secondary-fixed': '#2c0051',
        'surface-tint': '#c0c1ff',
        'on-tertiary-fixed': '#001e2f',
        'inverse-primary': '#494bd6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        unit: '4px',
        'margin-desktop': '40px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        'headline-xl': ['Geist', 'system-ui', 'sans-serif'],
        'headline-lg': ['Geist', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'system-ui', 'sans-serif'],
        'headline-md': ['Geist', 'system-ui', 'sans-serif'],
        'body-lg': ['Geist', 'system-ui', 'sans-serif'],
        'body-md': ['Geist', 'system-ui', 'sans-serif'],
        'body-sm': ['Geist', 'system-ui', 'sans-serif'],
        'label-md': ['Geist', 'system-ui', 'sans-serif'],
        'code-sm': ['Geist', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-sm': ['13px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
